### ISSUE TITLE
About dataset mask being empty

### ISSUE THREAD

**Issue by tangpanyu** [robert1003/slot-attention-disentanglement#38]
I used your coco data set processing method, but I rewritten it into the paddle framework, which is also a framework for deep learning. After I used it, I found that under your method, there is a data set with an empty mask. Have you not encountered this situation?

**Comment by as821** [comment]
Hello, we run experiments.py to filter out images with empty masks before running any other scripts. Please see the logic [here](https://github.com/robert1003/slot-attention-disentanglement/blob/master/pytorch/experiments.py#L66) for reference.  Filtering invalid masks from inside a dataset object is awkward so we do it in a preprocessing set.
