### ISSUE TITLE
about FG-ARI

### ISSUE THREAD

**Issue by tangpanyu** [robert1003/slot-attention-disentanglement#39]
Thank you for your excellent work. I would like to ask whether FG-ARI takes the maximum or the average? Because it seems that my experimental ARI is very different.

**Comment by as821** [comment]
Thank you for your interest in our work.

 The ARI reported in the paper is the average over the images in dataset. 

Our ARI implementation can be found [here](https://github.com/robert1003/slot-attention-disentanglement/blob/master/pytorch/metrics.py#L5). For questions about how ARI is calculated for the paper, please search for usages of this function in this repository.
